from tkinter import *
import math

f=Tk()
f.title("first calculator")
f.config(background='grey')
def hasnain(event):

    global var
    text=event.widget.cget("text")
    if text=="=":
        v=var.get().replace(chr(247),'/')
        va=v.replace('x','*')
        try:
            value=eval(va)
            var.set(value)
        except Exception as e:
            var.set("ERROR")
    elif text=="C":
        var.set("")

    elif text=="DEL":
        l=len(var.get())

        value=var.get().removesuffix(var.get()[l-1])
        var.set(value)

    else:
        var.set((var.get())+str(text))

# hasan.geometry("1100x600")
var=StringVar()
var.set((""))

l=Label(f,text="powered by saeed",bg="white").grid(row=6,column=8)
screen=Entry(f,textvariable=var,font="bold",borderwidth=10).grid(row=0,column=0,columnspan=15,pady=20,ipady=20)
b=Button(f,text="0",borderwidth=20,bg="grey")
b.grid(row=5,column=1)
b.bind('<Button-1>',hasnain)
b=Button(f,text="1",borderwidth=20,bg="grey")
b.grid(row=2,column=0)
b.bind('<Button-1>',hasnain)
b=Button(f,text="2",borderwidth=20,bg="grey")
b.grid(row=2,column=1)
b.bind('<Button-1>',hasnain)
b=Button(f,text="3",borderwidth=20,bg="grey")
b.grid(row=2,column=2)
b.bind('<Button-1>',hasnain)
b=Button(f,text="4",borderwidth=20,bg="grey")
b.grid(row=3,column=0)
b.bind('<Button-1>',hasnain)
b=Button(f,text="5",borderwidth=20,bg="grey")
b.grid(row=3,column=1)
b.bind('<Button-1>',hasnain)
b=Button(f,text="6",borderwidth=20,bg="grey")
b.grid(row=3,column=2)
b.bind('<Button-1>',hasnain)
b=Button(f,text="7",borderwidth=20,bg="grey")
b.grid(row=4,column=0)
b.bind('<Button-1>',hasnain)
b=Button(f,text="8",borderwidth=20,bg="grey")
b.grid(row=4,column=1)
b.bind('<Button-1>',hasnain)
b=Button(f,text="9",borderwidth=20,bg="grey")
b.grid(row=4,column=2)
b.bind('<Button-1>',hasnain)
b=Button(f,text="+",borderwidth=20,bg="grey")
b.grid(row=2,column=3)
b.bind('<Button-1>',hasnain)
b=Button(f,text="+",borderwidth=20,bg="grey")
b.grid(row=3,column=3)
b.bind('<Button-1>',hasnain)
b=Button(f,text="=",borderwidth=20,bg="skyblue")
b.grid(row=3,column=4)
b.bind('<Button-1>',hasnain)
b=Button(f,text="-",borderwidth=20,bg="grey")
b.grid(row=3,column=3)
b.bind('<Button-1>',hasnain)
b=Button(f,text='x',borderwidth=20,bg="grey")
b.grid(row=4,column=3)
b.bind('<Button-1>',hasnain)
b=Button(f,text=chr(247),borderwidth=20,bg="grey")
b.grid(row=5,column=3)
b.bind('<Button-1>',hasnain)
b=Button(f,text="C",borderwidth=20,bg="grey")
b.grid(row=5,column=2)
b.bind('<Button-1>',hasnain)
b=Button(f,text="DEL",borderwidth=20,bg="red")
b.grid(row=2,column=4)
b.bind('<Button-1>',hasnain)
b=Button(f,text=".",borderwidth=20,bg="grey")
b.grid(row=5,column=0)
b.bind('<Button-1>',hasnain)
b=Button(f,text="(",borderwidth=20,bg="grey")
b.grid(row=4,column=4)
b.bind('<Button-1>',hasnain)
b=Button(f,text=")",borderwidth=20,bg="grey")
b.grid(row=5,column=4)
b.bind('<Button-1>',hasnain)
b=Button(f,text=")",borderwidth=20,bg="grey")
b.grid(row=5,column=4)
b.bind('<Button-1>',hasnain)
mainloop()
